### ISSUE TITLE
"Register with FIWARE" links to wrong formular

### ISSUE THREAD

**Issue by Ape-Decendent** [Profirator/tenant-manager#4]
1.) Go to https://apis.2019.smartmaas.services/ (make sure you are not already registered with FIWARE).
2.) Click on the right upper green button which says "Sign up". https://apis.2019.smartmaas.services/sign-up shows up.
3.) Click on "Register With Fiware" (BTW should be renamed to "Register with FIWARE").

A new pop-up for signing-in appears. But instead it should be the registration form you would get when clicking on "Sign up" below the "Sign in" form.

**Comment by ilarimikkonen** [comment]
@Ape-Decendent this is not a tenant-manager issue. closing
